import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>frontendmentor.io practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Link className="text-cyan-300" href="/newbie">
          Newbie Challenges
        </Link>
      </main>
    </>
  );
}
